#!/usr/bin/env python3
"""
refresh_nhl_stats.py — regenerate nhl_stats.json from the NHL public API
standings endpoint. Computes goals-for/game and goals-against/game per team
and writes the file the app reads. No auth, no key.

    python3 refresh_nhl_stats.py

The web app never calls this in the request path — it only reads the file this
produces. Run it manually or on a daily schedule. Stdlib only.
"""
import json
import os
import time
import urllib.request

# NHL public standings endpoint (no key). "/now" = current; or a dated version.
STANDINGS_URL = "https://api-web.nhle.com/v1/standings/now"

OUT_PATH = os.environ.get("NHL_STATS_PATH",
                          os.path.join(os.path.dirname(os.path.abspath(__file__)), "nhl_stats.json"))


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "LineLogic/1.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read().decode("utf-8"))


def build(payload):
    teams = []
    for t in payload.get("standings", []):
        try:
            gp = float(t.get("gamesPlayed") or 0)
            gf_total = float(t.get("goalFor"))
            ga_total = float(t.get("goalAgainst"))
        except (TypeError, ValueError):
            continue
        if gp <= 0:
            continue
        name = (t.get("teamName") or {}).get("default")
        if not name:
            continue
        entry = {
            "name": name,
            "gf": round(gf_total / gp, 2),
            "ga": round(ga_total / gp, 2),
        }
        if t.get("wins") is not None:
            entry["record"] = f"{t.get('wins')}-{t.get('losses')}-{t.get('otLosses')}"
        if t.get("pointPctg") is not None:
            entry["points_pct"] = round(float(t["pointPctg"]), 3)
        teams.append(entry)
    teams.sort(key=lambda x: x["name"])
    return teams


def main():
    payload = fetch(STANDINGS_URL)
    teams = build(payload)
    doc = {"_comment": f"Auto-generated by refresh_nhl_stats.py — {time.strftime('%Y-%m-%d %H:%M')}. "
                       "gf/ga = goals for/against per game, from the NHL public API standings.",
           "teams": teams}
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    print(f"wrote {len(teams)} teams -> {OUT_PATH}")


if __name__ == "__main__":
    main()
