#!/usr/bin/env python3
"""
refresh_ncaa_stats.py — regenerate ncaa_stats.json from the free NCAA API
(henrygd/ncaa-api). Pulls team Runs and team ERA across ALL pages, computes
runs/game, maps NCAA names to your site's names, and writes ncaa_stats.json.

Run it manually or on a daily schedule (cron, a Railway cron service, or a
once-a-day background tick). The web app NEVER calls this in the request path —
it only ever reads the file this produces, so there's no quota or crash risk.

    python3 refresh_ncaa_stats.py

Stdlib only (urllib) — no extra dependencies.
"""
import json
import os
import re
import sys
import time
import urllib.request

# --- PASTE YOUR TWO TEAM-STAT URLs HERE (the henrygd ones you opened) ---------
# The "Runs" (team offense) category and the "Earned Run Average" category.
# They look like: https://ncaa-api.henrygd.me/stats/baseball/d1/current/team/<id>
RUNS_URL = "https://ncaa-api.henrygd.me/stats/baseball/d1/current/team/486"   # team Runs
ERA_URL  = "https://ncaa-api.henrygd.me/stats/baseball/d1/current/team/211"   # team ERA

OUT_PATH = os.environ.get("NCAA_STATS_PATH",
                          os.path.join(os.path.dirname(os.path.abspath(__file__)), "ncaa_stats.json"))

# NCAA name -> your site's label. Most names match or fuzzy-match fine; only the
# ones that genuinely differ need an entry. Extend as you spot mismatches.
ALIASES = {
    "Southern California": "USC",
    "St. John's (NY)": "Saint John's",
    "Mississippi St.": "Mississippi State",
    "Little Rock": "Little Rock",
}


def _norm(name):
    n = (name or "").lower().replace("&", "and")
    n = re.sub(r"[^a-z0-9 ]", "", n)
    n = re.sub(r"\s+", " ", n).strip()
    return n


def fetch_all(url):
    """Fetch every page of a henrygd stats endpoint, return combined data rows."""
    if not url or url.startswith("PASTE_"):
        raise SystemExit("Set RUNS_URL and ERA_URL at the top of this script first.")
    rows, page, pages = [], 1, 1
    while page <= pages:
        sep = "&" if "?" in url else "?"
        req = urllib.request.Request(url + f"{sep}page={page}",
                                     headers={"User-Agent": "LineLogic/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            payload = json.loads(r.read().decode("utf-8"))
        rows.extend(payload.get("data", []))
        pages = int(payload.get("pages", 1) or 1)
        page += 1
        time.sleep(0.3)  # be polite; well under the 5 req/sec public limit
    return rows


def parse_runs(rows):
    """{norm_name: (display_name, runs_per_game)} from the Runs table."""
    out = {}
    for d in rows:
        team = d.get("Team")
        try:
            g = float(d.get("G")); r = float(d.get("R"))
        except (TypeError, ValueError):
            continue
        if not team or g <= 0:
            continue
        out[_norm(team)] = (team, round(r / g, 1))
    return out


def parse_era(rows):
    """{norm_name: era} from the ERA table."""
    out = {}
    for d in rows:
        team = d.get("Team")
        try:
            era = float(d.get("ERA"))
        except (TypeError, ValueError):
            continue
        if not team:
            continue
        out[_norm(team)] = era
    return out


def build(runs_rows, era_rows):
    runs = parse_runs(runs_rows)
    era = parse_era(era_rows)
    teams = []
    for key, (display, rpg) in sorted(runs.items()):
        site_name = ALIASES.get(display, display)
        entry = {"name": site_name, "rpg": rpg}
        if key in era:
            entry["era"] = era[key]
        teams.append(entry)
    return teams


def main():
    runs_rows = fetch_all(RUNS_URL)
    era_rows = fetch_all(ERA_URL)
    teams = build(runs_rows, era_rows)
    doc = {"_comment": f"Auto-generated by refresh_ncaa_stats.py — {time.strftime('%Y-%m-%d %H:%M')}. "
                       "rpg = runs/game, era = team ERA, from the NCAA API (henrygd). Names mapped to site labels via ALIASES.",
           "teams": teams}
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    with_era = sum(1 for t in teams if "era" in t)
    print(f"wrote {len(teams)} teams ({with_era} with ERA) -> {OUT_PATH}")


if __name__ == "__main__":
    main()
